openapi: 3.1.0
info:
  title: Account Movements API
  description: API para gestionar movimientos de cuenta
  version: "1.0"
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /api/v1/movements:
    get:
      tags:
      - movement-controller
      operationId: getAllMovements
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MovementDetailDTO"
    post:
      tags:
      - movement-controller
      operationId: createMovement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MovementRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MovementDetailDTO"
  /api/v1/movements/{id}:
    get:
      tags:
      - movement-controller
      operationId: getMovementById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MovementDetailDTO"
  /api/v1/movements/reports/{clientId}:
    get:
      tags:
      - report-controller
      operationId: getAccountStatement
      parameters:
      - name: clientId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: startDate
        in: query
        required: true
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountDTO"
  /api/v1/movements/reports/{clientId}/excel:
    get:
      tags:
      - report-controller
      operationId: downloadExcelReport
      parameters:
      - name: clientId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: startDate
        in: query
        required: true
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
components:
  schemas:
    MovementRequestDto:
      type: object
      properties:
        type:
          type: string
          minLength: 1
          pattern: DEBIT|CREDIT
        value:
          type: number
          minimum: 0.00
        accountNumber:
          type: string
          maxLength: 20
          minLength: 5
      required:
      - value
    MovementDetailDTO:
      type: object
      properties:
        date:
          type: string
          format: date-time
        type:
          type: string
        value:
          type: number
        balance:
          type: number
    AccountDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        initialBalance:
          type: number
          format: double
        clientId:
          type: integer
          format: int64
        type:
          type: string
        movements:
          type: array
          items:
            $ref: "#/components/schemas/MovementDetailDTO"
