openapi: 3.0.3
info:
  title: Account Movements API
  description: "API para gestionar clientes, cuentas y movimientos"
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/customers/{id}:
    get:
      tags:
      - client-controller
      operationId: getClientById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Client"
    put:
      tags:
      - client-controller
      operationId: updateClient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Client"
    delete:
      tags:
      - client-controller
      operationId: deleteClient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/accounts/{id}:
    get:
      tags:
      - account-controller
      operationId: getAccountById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Account"
    put:
      tags:
      - account-controller
      operationId: updateAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Account"
    delete:
      tags:
      - account-controller
      operationId: deleteAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/movements:
    get:
      tags:
      - movement-controller
      operationId: getAllMovements
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movement"
    post:
      tags:
      - movement-controller
      operationId: createMovement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Movement"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Movement"
  /api/v1/customers:
    get:
      tags:
      - client-controller
      operationId: getAllClients
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
    post:
      tags:
      - client-controller
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Client"
  /api/v1/accounts:
    get:
      tags:
      - account-controller
      operationId: getAllAccounts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
    post:
      tags:
      - account-controller
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Account"
  /api/v1/movements/{id}:
    get:
      tags:
      - movement-controller
      operationId: getMovementById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Movement"
  /api/v1/movements/reports/{clientId}:
    get:
      tags:
      - report-controller
      operationId: getAccountStatement
      parameters:
      - name: clientId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: startDate
        in: query
        required: true
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountDTO"
  /api/v1/movements/reports/{clientId}/excel:
    get:
      tags:
      - report-controller
      operationId: downloadExcelReport
      parameters:
      - name: clientId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: startDate
        in: query
        required: true
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
components:
  schemas:
    Client:
      type: object
      properties:
        name:
          type: string
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        id:
          type: integer
          format: int64
        password:
          type: string
        status:
          type: boolean
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        type:
          type: string
        initialBalance:
          type: number
          format: double
        status:
          type: boolean
        client:
          $ref: "#/components/schemas/Client"
    Movement:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date-time
        type:
          type: string
        value:
          type: number
          format: double
        balance:
          type: number
          format: double
        account:
          $ref: "#/components/schemas/Account"
    AccountDTO:
      type: object
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        currentBalance:
          type: number
          format: double
        movements:
          type: array
          items:
            $ref: "#/components/schemas/MovementDetailDTO"
    MovementDetailDTO:
      type: object
      properties:
        date:
          type: string
          format: date-time
        type:
          type: string
        value:
          type: number
          format: double
        balance:
          type: number
          format: double
